CASCAS_DISPONIVEIS = ['PRETO', 'BRANCO']

TAMANHO_DISPONIVEL = [250, 500]

RECHEIO_DISPONIVEL = ['BRIGADEIRO', 'BRANQUINHO', 'brigadeiro', 'branquinho']

PEDIDO_CASCA = []

PEDIDO_TAMANHO = []

PEDIDO_RECHEIO = []

PEDIDO = [PEDIDO_CASCA, PEDIDO_TAMANHO, PEDIDO_RECHEIO]